### ISSUE TITLE
pyaff4 version inaccurate?

### ISSUE THREAD

**Issue by PoorBillionaire** [google/aff4#30]
Greetings--

This afternoon I noticed that the pyaff4 packages differ between what's being hosted on GitHub and the latest package on PyPI; however both packages report the same version string:  0.24.post3.

I see you're auto-generating the version string programatically, so I won't submit a pull request to update anything. If I'm missing anything please let me know.

--
Adam

**Comment by scudette** [comment]
The current version on github is 0.25 rc1:
https://github.com/google/aff4/blob/master/pyaff4/version.yaml

Indeed it is not pushed to pypi yet. I am planning on making a release very soon.

**Comment by scudette** [comment]
Oh I see what you mean. Ha I must have missed it. Bradley has directly modified version.yaml without using the automated tool which syncs it into the package :-). https://github.com/google/aff4/commit/0c9dafbed1ea63c275f7d7efbed0f78b928fcbb4

Thanks.

**Comment by PoorBillionaire** [comment]
This is resolved - thanks Michael
