### ISSUE TITLE
pyaff4 extra print statement

### ISSUE THREAD

**Issue by PoorBillionaire** [google/aff4#32]
Greetings--

On [line 96](https://github.com/google/aff4/blob/master/pyaff4/pyaff4/container.py#L96) of container.py, there is a seemingly extraneous print statement which outputs data whenever that block is reached.

This manifests as a minor inconvenience when I use Volatility's AFF4 address space, as this data is output alongside my Volatility results.

Would it be possible to remove the print statement, or is there a need for it to be there? Thanks!

--
Adam

**Comment by PoorBillionaire** [comment]
...I'm pretty sure I was wrong about where the extra data is coming from. I'll have to go back and look again.

**Comment by PoorBillionaire** [comment]
Nope, it's definitely line 96 of container.py. I need to look into whether or not 'lex == lexicon.scudette' should be evaluating True under normal circumstances, but I may not have time tonight.

**Comment by scudette** [comment]
Yes sorry that must have been some debugging left over. I will remove.

**Comment by PoorBillionaire** [comment]
Looks good, thank you
